"""Global changes

Revision ID: dd30e19648a3
Revises: c5b577fa906f
Create Date: 2026-01-19 18:50:30.400724

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd30e19648a3"
down_revision: Union[str, Sequence[str], None] = "c5b577fa906f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("currency", sa.Text(), server_default="usd", nullable=False)
    )
    op.drop_constraint("valid_status", "events_participants", type_="check")
    op.create_check_constraint(
        "valid_status",
        "events_participants",
        "status IN ('booked', 'confirmed', 'cancelled')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("valid_status", "events_participants", type_="check")
    op.create_check_constraint(
        "valid_status",
        "events_participants",
        "status IN ('confirmed', 'cancelled')"
    )
    op.drop_column("events", "currency")
    # ### end Alembic commands ###
